# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'BeeQuick' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BeeQuick

  pod 'SDWebImage'
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'SVProgressHUD'
  pod 'YYModel'
  pod 'FMDB'
  pod 'SDCycleScrollView'
  pod 'UMengUShare/UI'
  pod 'UMengUShare/Social/Sina'
  pod 'UMengUShare/Social/WeChat'
  pod 'UMengUShare/Social/QQ'
  
end
